config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  root to: 'home#top'
  get "/home/about" => "home#about"
  get 'search' => 'searches#search'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
  	resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :destroy, :index, :new] do
    member do
     get :following, :followers
    end
  end

  post 'create/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'destroy/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where("#{word}")
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
	end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	belongs_to :user
	belongs_to :book

	validates :comment, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人 
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :name, presence: true
  validates :introduction, length: {maximum: 50}

    # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end


  def self.search(search,word)
        if search == "forward_match"
                        @user = User.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
                        @user = User.where("name LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @user = User.where("#{word}")
        elsif search == "partial_match"
                        @user = User.where("name LIKE?","%#{word}%")
        else
                        @user = User.all
           end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!,except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
	book = Book.find(params[:book_id])
	comment = BookComment.new(book_comment_params)
	comment.user_id = current_user.id
	comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
	end

	def destroy
		BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])

	end

	private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_book, only: [:edit]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = @book.user
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

    def index
    @book = Book.new
    @user = @book.user
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def correct_book
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def create
	book = Book.find(params[:book_id])
	favorite = current_user.favorites.new(book_id: book.id)
	favorite.save
	redirect_back fallback_location: root_path
end

def destroy
	book = Book.find(params[:book_id])
	favorite = current_user.favorites.find_by(book_id: book.id)
	favorite.destroy
	redirect_back fallback_location: root_path
end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	current_user.follow(params[:id])
  redirect_back fallback_location: root_path
  end

  def destroy
  current_user.unfollow(params[:id])
  redirect_back fallback_location: root_path
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

 def search
 	@range = params[:range]
 	search = params[:search]
 	word = params[:word]

 	if @range == "1"
 		@user= User.search(search,word)
 	else
 		@book = Book.search(search,word)
 	end
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @users = User.all
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.follower
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followed
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<% if @book.errors.any? %>
		<div id="error_explanation">
			<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<%= form_for(@book) do |f| %>
	<div class="field row">
		<p>Title</p>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<p>Opinion</p>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<h2>New book</h2>
		<%= render 'books/newform', book: @books %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
					<% if book.favorited_by?(current_user) %>
						  <%= link_to book_favorites_path(book), method: :delete do %>
						    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
						    <%= book.favorites.count %>
						  <% end %>
						<% else %>
						 <%= link_to book_favorites_path(book), method: :post do %>
						  <i class="far fa-heart" aria-hidden="true"></i>
						    <%= book.favorites.count %>
						  <% end %>
						  <% end %>
						</td>
					<td><%= book.book_comments.count %>件コメント</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<% if @book.user == current_user %>
					<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
					<td>
					<% if @book.favorited_by?(current_user) %>
						  <%= link_to book_favorites_path(@book), method: :delete do %>
						    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
						    <%= @book.favorites.count %>
						  <% end %>
						<% else %>
						 <%= link_to book_favorites_path(@book), method: :post do %>
						  <i class="far fa-heart" aria-hidden="true"></i>
						    <%= @book.favorites.count %>
						  <% end %>
						  <% end %>
						</td>
					<td><%= @book.book_comments.count %>件コメント</td>
				</tr>
			</table>

			<table class="table">
		<% @book.book_comments.each do |book_comment| %>
				<tr>
					<td>
						<%= link_to user_path(book_comment.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
						<% end %>
						<%= book_comment.comment %>
						<% if book_comment.user == current_user %>
              				<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
						<br>
						<%= book_comment.user.name %>
			            </tb>
			          <% end %>
					<% end %>
				</tr>
			</table>

			<%= form_for [@book, @book_comment] do |f| %>
                      <tr>
                      	<tb>
                      		<div class="row">
                        <div class="col-sm-12">
                          <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                        </div>
                      </div>
                      <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
                  </tb>
                  </tr>
                    <% end %>


	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/searches/search.html.erb
<h2>Results index</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
　<% if @range == '2' %>
  <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
     <% @book.each do |book| %>
     <tr>
      <td>
       <%= link_to(book.user) do %>
       <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
       <% end %>
      </td>
      <td>
       <%= link_to book.title, book, class: "book_#{book.id}" %> 
      </td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
  </tbody>

  <% else %>
  <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
     <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
      <td><%= user.name%></td>
      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
     </tr>
    <% end %>
   </tbody>
   <% end %>
 </table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<tr>
		<th>follows</th>
		<th><%= link_to following_user_path(user) do %>
		<%= user.follower.count %></th>
		<% end %>
	</tr>

	<tr>
		<th>followers</th>
		<th><%= link_to followers_user_path(user) do %>
		<%= user.followed.count %></th>
		<% end %>
	</tr>

</table>
<div class="row">

<% if user != current_user %>
<% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-primary col-xs-12"%>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-success col-xs-12" %>
      <% end %>

      <% else %>


	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(@user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name %></td>
						<td><%= "フォロー数: #{user.follower.count}" %></td>
						<td><%= "フォロワー数: #{user.followed.count}" %></td>
						<td><% if user != current_user %>
							<% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %><% end %></td>
						<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td><%= book.book_comments.count %>件コメント</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

app/views/users/show_follow.html.erb
<div class="col-xs-12">
	<h1>Follow Users</h1>
	<% if @user.follower.count == 0 %>
		<span>ユーザーはいません</span>

		<% else %>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

	<% @user.following_user.each do |user| %>

			<tbody>
				<td><%= attachment_image_tag(@user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td><%= "フォロー数: #{@user.follower.count}" %></td>
				<td><%= "フォロワー数: #{@user.followed.count}" %></td>
				<td><%= link_to 'show', user_path(user) %></td>
				<tr>
				</tr>
			</tbody>
				<% end %>

		</table>

	<% end %>
</div>

app/views/users/show_follower.html.erb
<div class="col-xs-12">
	<h1>Follower Users</h1>
	<% @user.follower_user.each do |user| %>
    <p>

	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<td><%= attachment_image_tag(@user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name %></td>
			<td><%= "フォロー数: #{@user.follower.count}" %></td>
			<td><%= "フォロワー数: #{@user.followed.count}" %></td>
			<td><%= link_to 'show', user_path(user) %></td>
			<tr>
			</tr>
		</tbody>

	</table>
	<% end %>
</div>