config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  root to: 'home#top'
  get "/home/about" => "home#about"
  get 'search' => 'searches#search'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
  	resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :destroy, :index, :new] do
    member do
     get :following, :followers
    end
  end

  post 'create/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'destroy/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where("#{word}")
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
	end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	belongs_to :user
	belongs_to :book

	validates :comment, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人 
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :name, presence: true
  validates :introduction, length: {maximum: 50}

    # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end


  def self.search(search,word)
        if search == "forward_match"
                        @user = User.where("name LIKE?","#{word}%")
        elsif search == "backward_match"
                        @user = User.where("name LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @user = User.where("#{word}")
        elsif search == "partial_match"
                        @user = User.where("name LIKE?","%#{word}%")
        else
                        @user = User.all
           end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!,except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_book, only: [:edit]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = @book.user
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

    def index
    @book = Book.new
    @user = @book.user
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def correct_book
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def create
	book = Book.find(params[:book_id])
	favorite = current_user.favorites.new(book_id: book.id)
	favorite.save
	redirect_back fallback_location: root_path
end

def destroy
	book = Book.find(params[:book_id])
	favorite = current_user.favorites.find_by(book_id: book.id)
	favorite.destroy
	redirect_back fallback_location: root_path
end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

 def search
 	@range = params[:range]
 	search = params[:search]
 	word = params[:word]

 	if @range == "1"
 		@user= User.search(search,word)
 	else
 		@book = Book.search(search,word)
 	end
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @users = User.all
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.follower
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followed
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to 'users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to 'books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to 'Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to 'About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to 'sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to 'login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <div class="container">
      <p id="notice"><%= notice %></p>
    </div>

<% if user_signed_in? %>

   <%= form_tag(search_path, method: :get) do %>
   <div class='container'>
        <div class='row'>
          <div class='col-md-12 '>

      　<tr>
        <td><%= text_field_tag (:word) %></td>

        <td><%= select_tag 'range' ,options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']]) %></td>

   　　<td><%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %></td>
      　　 <td><%= submit_tag "検索" %></td>

      </tr>
    </div>
  </div>
</div>

   <% end %>

<% end %>

    <body>
      <div class='container'>
        <div class='row'>
          <div class='col-md-12 '>
    　<%= yield %>
          </div>
        </div>
      </div>
  　</body>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>